Repository openclarity/openclarity, pull requests merged in 2024-11, with the labels that each got.

#908 fix(helm): installation error with externalPostgresql
  installation/kubernetes/helm/openclarity/templates/apiserver/deployment.yaml
Labels: size/XS

#912 fix(ci): drop explicit PR scope check
  .github/workflows/pr.yml
Labels: size/S

#915 release(general): prepare release v1.1.1
  api/client/go.mod
  api/server/go.mod
  api/types/go.mod
  cli/go.mod
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/types/go.mod
  e2e/go.mod
  installation/go.mod
  orchestrator/go.mod
  plugins/runner/go.mod
  plugins/sdk-go/example/go.mod
  plugins/store/kics/go.mod
  provider/go.mod
  scanner/go.mod
  testenv/go.mod
  uibackend/client/go.mod
  uibackend/server/go.mod
  utils/go.mod
  versions.yaml
Labels: size/M
