Repository openclarity/openclarity, pull requests merged in 2024-10, with the labels that each got.

#879 fix(ci): sed command fails in release wf
  Makefile
Labels: size/XS

#883 docs(general): update slack link
  README.md
Labels: size/XS

#887 feat(k8s): use scanner image with arm64 support
  provider/kubernetes/scanner/scanner.go
Labels: size/XS

#889 fix(cli): check SBOM result before writing
  cli/presenter/writer_test.go
  scanner/families/sbom/types/result.go
Labels: bug, size/M, kind/bug

#888 fix(helm): external postgresql port quotes
  installation/kubernetes/helm/openclarity/templates/apiserver/deployment.yaml
Labels: bug, size/XS

#895 release(general): prepare release v1.1.0
  api/client/go.mod
  api/server/go.mod
  api/types/go.mod
  cli/go.mod
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/types/go.mod
  e2e/go.mod
  installation/go.mod
  orchestrator/go.mod
  plugins/runner/go.mod
  plugins/sdk-go/example/go.mod
  plugins/store/kics/go.mod
  provider/go.mod
  scanner/go.mod
  testenv/go.mod
  uibackend/client/go.mod
  uibackend/server/go.mod
  utils/go.mod
  versions.yaml
Labels: size/M

#897 fix(scanner): panic when nil result
  scanner/families/sbom/types/result.go
Labels: bug, size/XS, area/scanner

#896 chore(general): bump go
  .go-version
  api/client/go.mod
  api/server/go.mod
  api/types/go.mod
  cli/go.mod
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/types/go.mod
  core/go.mod
  e2e/go.mod
  e2e/testdata/go.mod
  installation/go.mod
  orchestrator/go.mod
  plugins/runner/go.mod
  plugins/sdk-go/example/go.mod
  plugins/sdk-go/go.mod
  plugins/store/kics/go.mod
  provider/go.mod
  scanner/go.mod
  testenv/go.mod
  uibackend/client/go.mod
  uibackend/server/go.mod
  uibackend/types/go.mod
  utils/go.mod
  workflow/go.mod
Labels: size/S

#907 fix(ui): Fixed issue with blank page when `image` information is missed in assetInfo
  ui/src/layout/AssetScans/AssetScansTable.jsx
  ui/src/layout/Assets/AssetsForFindingTable.jsx
  ui/src/layout/Assets/AssetsTable.jsx
Labels: size/XS
