Repository openclarity/openclarity, pull requests merged in 2024-08, with the labels that each got.

#754 refactor(ui): update project with OpenClarity branding
  ui/index.html
  ui/package.json
  ui/public/favicon.png
  ui/public/manifest.json
  ui/src/api/axiosClient.ts
  ui/src/api/openClarityApi.ts
  ui/src/api/vmClarityApi.ts
  ui/src/layout/App/app.scss
  ui/src/layout/App/index.jsx
  ui/src/layout/Dashboard/EmptyScansDisplay.jsx
  ui/src/layout/Scans/Configurations/ConfigurationsTable/index.jsx
  ui/src/layout/Scans/ScanConfigWizardModal/StepAdvancedSettings.jsx
  ui/src/layout/Scans/Scans/ScansTable.jsx
  ui/src/layout/Scans/index.jsx
  ui/src/utils/images/brand.png
  ui/src/utils/images/brand.svg
Labels: component:ui

#755 refactor(docker): rename docker images modules to openclarity
  .families.yaml
  .github/workflows/image-cleanup.yml
  .github/workflows/reusable-end-to-end-testing.yml
  Makefile
  api/server/cmd/main.go
  containerruntimediscovery/server/cmd/main.go
  docker-bake.hcl
  e2e/config/config_test.go
  installation/aws/VmClarity.cfn
  installation/azure/vmclarity-UI.json
  installation/azure/vmclarity.bicep
  installation/azure/vmclarity.json
  installation/azure/vmclarityDeployModule.bicep
  installation/docker/docker-compose.yml
  installation/docker/image_override.env
  installation/docker/orchestrator.env
  installation/gcp/dm/components/vmclarity-server.py.schema
  installation/gcp/dm/vmclarity.py.schema
  installation/kubernetes/helm/vmclarity/README.md
  installation/kubernetes/helm/vmclarity/values.yaml
  orchestrator/cmd/main.go
  plugins/README.md
  provider/cloudinit/cloudinit_test.go
  provider/cloudinit/testdata/cloud-init.yaml
  testenv/config.go
  testenv/docker/docker_test.go
  testenv/kubernetes/helm/chart_test.go
  testenv/testenv_test.go
  testenv/types/containerimages_test.go
  uibackend/server/cmd/main.go
  uibackend/server/dashboard_riskiest_assets_test.go
Labels: docker

#774 fix(ci): use github token instead of pat in image cleanup workflow
  .github/workflows/image-cleanup.yml
Labels: ci

#762 feat(e2e): Add benchmarking
  .github/workflows/reusable-end-to-end-testing.yml
  e2e/README.md
  e2e/benchmark/benchmark_extractor.go
  e2e/benchmark/config.go
  e2e/config/config.go
  e2e/config/config_test.go
  e2e/full_scan_test.go
  e2e/go.mod
  e2e/go.sum
Labels: enhancement, go, ci

#761 refactor(ui): switch useFetch for TanStack queries
  ui/package-lock.json
  ui/package.json
  ui/src/api/constants.ts
  ui/src/components/Form/index.jsx
  ui/src/hooks/index.js
  ui/src/hooks/useDelete.js
  ui/src/hooks/useMountMultiFetch.js
  ui/src/hooks/useMultiFetch.js
  ui/src/layout/App/index.jsx
  ui/src/layout/Dashboard/CounterDisplay/index.jsx
  ui/src/layout/Dashboard/FindingsTrendsWidget/index.jsx
  ui/src/layout/Dashboard/RiskiestRegionsWidget/index.jsx
  ui/src/layout/Dashboard/index.jsx
  ui/src/layout/Findings/AssetCountDisplay.jsx
  ui/src/layout/Scans/Configurations/ConfigurationActionsDisplay/index.jsx
  ui/src/layout/Scans/Configurations/ConfigurationDetails/TabConfiguration.jsx
  ui/src/layout/Scans/Scans/ScanActionsDisplay/index.jsx
  ui/src/layout/Scans/index.jsx
  ui/src/layout/detail-displays/AssetDetails/AssetScansDisplay.jsx
Labels: javascript

#776 fix(api): empty arch failure when vm discovered
  api/types/asset.go
  provider/aws/discoverer/discoverer.go
Labels: bug

#786 feat(cli): migrate KubeClarity command
  cli/cmd/asset/asset_create.go
  cli/cmd/asset/asset_scan_create.go
  cli/cmd/convert/convert.go
  cli/cmd/root/root.go
  cli/cmd/scan/scan.go
  cli/presenter/openclarity.go
  cli/state/openclarity.go
  cli/state/openclarity_test.go
  cli/test/boot/README.md
  cli/test/boot/vagrant/cloud-config.cfg
Labels: enhancement, go

#789 feat(ci): add support for self-hosted renovate
  .github/workflows/dependencies.yml
  Makefile
  makefile.d/20-tools.mk
  renovate.json
Labels: enhancement, github_actions

#803 refactor(api): remove scanner name from misconfig and info finder
  api/openapi.yaml
  api/server/database/gorm/odata.go
  api/server/internal/server/server.gen.go
  api/types/go.mod
  api/types/plugin_adapter.go
  api/types/types.gen.go
  cli/presenter/apimodel.go
  cli/presenter/apimodel_test.go
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/types/go.mod
  orchestrator/processor/assetscan/infofinder.go
  orchestrator/processor/assetscan/misconfigurations.go
  rfc/extend-misconfiguration-scanners.md
  scanner/findingkey/common_test.go
  scanner/findingkey/infofinder.go
  scanner/findingkey/infofinder_test.go
  scanner/findingkey/misconfiguration.go
  ui/src/layout/Findings/Misconfigurations/TabMisconfigurationDetails.jsx
  uibackend/openapi.yaml
  uibackend/server/dashboard_findings_impact.go
  uibackend/server/internal/server/server.gen.go
  uibackend/types/types.gen.go
Labels: go

#804 chore(general): bump go to 1.22.6
  .go-version
  CONTRIBUTING.md
  api/client/go.mod
  api/server/go.mod
  api/types/go.mod
  cli/go.mod
  containerruntimediscovery/client/go.mod
  containerruntimediscovery/server/go.mod
  containerruntimediscovery/types/go.mod
  core/go.mod
  e2e/go.mod
  e2e/testdata/go.mod
  installation/go.mod
  orchestrator/go.mod
  plugins/runner/go.mod
  plugins/sdk-go/example/go.mod
  plugins/sdk-go/go.mod
  plugins/store/kics/go.mod
  provider/go.mod
  scanner/go.mod
  testenv/go.mod
  uibackend/client/go.mod
  uibackend/server/go.mod
  uibackend/types/go.mod
  utils/go.mod
  workflow/go.mod
Labels: go
